packages:
  - packages/*
  - fixtures/*
  - tests
  - test-helpers

dedupePeers: true
linkWorkspacePackages: deep
preferWorkspacePackages: true

allowBuilds:
  esbuild: false
  puppeteer: true
  unrs-resolver: false

minimumReleaseAgeExclude:
  - 'eslint-config-seek'
  - 'renovate-config-seek'
