packages:
  - packages/*
  - fixtures/*
  - tests
  - test-helpers

dedupePeers: true
linkWorkspacePackages: deep
preferWorkspacePackages: true

allowBuilds:
  esbuild: false
  puppeteer: true
  unrs-resolver: false

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - 'eslint-config-seek'
