name: Validate

on:
  - pull_request
  - push

jobs:
  validate:
    name: Lint & Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Check out repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up PNPM
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: pnpm
          node-version-file: package.json

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache Puppeteer
        id: puppeteer-cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: /home/runner/.cache/puppeteer
          key: puppeteer-${{ runner.os }}-${{ hashFiles('./pnpm-lock.yaml') }}

      - name: Install Puppeteer
        if: steps.puppeteer-cache.outputs.cache-hit != 'true'
        run: pnpm puppeteer browsers install chrome

      - name: Build
        run: pnpm build

      - name: Compile fixtures
        run: pnpm compile-fixtures

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

  validate-windows:
    name: Test on Windows
    runs-on: windows-latest
    env:
      CI: true
    steps:
      - name: Check out repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up PNPM
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: pnpm
          node-version-file: package.json

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache Puppeteer
        id: puppeteer-cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: C:\Users\runneradmin\.cache\puppeteer
          key: puppeteer-${{ runner.os }}-${{ hashFiles('./pnpm-lock.yaml') }}

      - name: Install Puppeteer
        if: steps.puppeteer-cache.outputs.cache-hit != 'true'
        run: pnpm puppeteer browsers install chrome

      - name: Build
        run: pnpm build

      - name: Compile fixtures
        run: pnpm compile-fixtures

      - name: Test
        run: pnpm test E2E
