name: Validate

on:
  - pull_request
  - push

jobs:
  validate:
    name: Lint & Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          cache: pnpm
          node-version-file: package.json

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache Puppeteer
        id: puppeteer-cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: /home/runner/.cache/puppeteer
          key: puppeteer-${{ runner.os }}-${{ hashFiles('./pnpm-lock.yaml') }}

      - name: Install Puppeteer
        if: steps.puppeteer-cache.outputs.cache-hit != 'true'
        run: pnpm puppeteer browsers install chrome

      - name: Build
        run: pnpm build

      - name: Compile fixtures
        run: pnpm compile-fixtures

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

  validate-windows:
    name: Test on Windows
    runs-on: windows-latest
    env:
      CI: true
    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          cache: pnpm
          node-version-file: package.json

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache Puppeteer
        id: puppeteer-cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: C:\Users\runneradmin\.cache\puppeteer
          key: puppeteer-${{ runner.os }}-${{ hashFiles('./pnpm-lock.yaml') }}

      - name: Install Puppeteer
        if: steps.puppeteer-cache.outputs.cache-hit != 'true'
        run: pnpm puppeteer browsers install chrome

      - name: Build
        run: pnpm build

      - name: Compile fixtures
        run: pnpm compile-fixtures

      - name: Test
        run: pnpm test E2E
